#!/usr/bin/env node
'use strict';
const fs=require('node:fs');
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const {Simulation,get,equal}=require('../assets/engine.js');
function execute(spec,request){const sim=new Simulation(spec);return (request.commands||[]).map(c=>{try{let state;switch(c.op){case'start':state=sim.start(c.scenario||spec.scenarios[0].id,c.mode||'normal');break;case'step':state=sim.step();break;case'run':state=sim.advance(c.limit);break;case'decide':state=sim.decide(c.value);break;case'back':state=sim.back();break;case'cancel':state=sim.cancel();break;case'reset':state=sim.reset();break;case'inspect':state=sim.inspect();break;default:throw Error('Unknown command '+c.op);}return{ok:true,state};}catch(e){return{ok:false,error:e.message,state:sim.inspect()};}});}
function acceptance(spec){const results=[];for(const c of spec.acceptance||[]){try{const sim=new Simulation(spec);sim.start(c.scenario,c.mode||'normal');sim.advance();for(const decision of c.decisions||[]){sim.decide(decision);sim.advance();}const r=sim.inspect(),e=c.expect;for(const k of ['status','nodeId'])if(e[k]!==undefined&&r[k]!==e[k])throw Error(k+': expected '+e[k]+' got '+r[k]);for(const [k,v]of Object.entries(e.context||{}))if(!equal(get(r.context,k),v))throw Error('context.'+k+' mismatch');for(const id of e.traceIncludes||[])if(!r.trace.some(t=>t.nodeId===id))throw Error('Missing trace node '+id);for(const id of e.traceExcludes||[])if(r.trace.some(t=>t.nodeId===id))throw Error('Unexpected trace node '+id);for(const event of r.trace.filter(t=>t.edgeId)){const edge=spec.edges.find(x=>x.id===event.edgeId);if(!edge||edge.kind==='data'||edge.target!==event.nodeId)throw Error('Noncanonical trace edge');}results.push({id:c.id,ok:true,status:r.status,steps:r.trace.length});}catch(e){results.push({id:c.id,ok:false,error:e.message});}}return results;}
if(require.main===module){try{const [file,flag]=process.argv.slice(2);if(!file)throw Error('Usage: node scripts/run.js spec.json [--test]');const checked=spawnSync(process.env.PYTHON||'python3',[path.join(__dirname,'diagram.py'),'validate',file],{encoding:'utf8'});if(checked.error)throw Error('Python 3.10+ required for spec validation: '+checked.error.message);if(checked.status!==0)throw Error(checked.stderr.trim()||'Invalid spec');const spec=JSON.parse(fs.readFileSync(file,'utf8'));let out;if(flag==='--test'){out=acceptance(spec);if(!out.length)throw Error('No acceptance cases');if(out.some(x=>!x.ok))process.exitCode=1;}else{const request=JSON.parse(fs.readFileSync(0,'utf8'));if(!request||!Array.isArray(request.commands))throw Error('Expected {commands:[...]}');out=execute(spec,request);if(out.some(x=>!x.ok))process.exitCode=1;}process.stdout.write(JSON.stringify(out,null,2)+'\n');}catch(e){process.stderr.write(e.message+'\n');process.exitCode=1;}}
module.exports={execute,acceptance};
