'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {loadOfficialRuntime}=require('./native-layout-runtime');const r=loadOfficialRuntime();
for(const f of ['source-presentation.js','focused-connections.js','visual-theme.js'])r.evaluateFile(path.join(__dirname,'../assets',f));
const spec=process.argv[2]?JSON.parse(fs.readFileSync(process.argv[2],'utf8')):{sourceModel:{},sourcePresentation:{overviewRoot:'root'},nodes:[{id:'root',role:'container'},{id:'a',role:'container',parent:'root'},{id:'nested',role:'container',parent:'a'},{id:'step',parent:'nested'},{id:'b',role:'container',parent:'root'},{id:'store',parent:'b'}],edges:[{id:'w1',source:'step',target:'store',kind:'data',relation:'write'},{id:'w2',source:'nested',target:'store',kind:'data',relation:'write'},{id:'r1',source:'store',target:'step',kind:'data',relation:'read'},{id:'c1',source:'step',target:'store',relation:'control'}]};
const before=JSON.stringify(spec),source=r.context.ProbeSourcePresentation,focus=r.context.ProbeFocusedConnections,lookup=focus.index(spec);
const data=spec.edges.filter(e=>e.kind==='data'),allMembers=lookup.groups.flatMap(g=>g.edges.map(e=>e.id));assert.equal(allMembers.length,data.length);assert.equal(new Set(allMembers).size,data.length);assert.deepEqual([...allMembers].sort(),data.map(e=>e.id).sort());
for(const g of lookup.groups){assert.ok(g.label.includes('条'));for(const e of g.edges)assert.deepEqual([lookup.module(e.source),lookup.module(e.target)].sort(),[g.source,g.target]);assert.equal(g.forward,g.edges.some(e=>lookup.module(e.source)===g.source));assert.equal(g.backward,g.edges.some(e=>lookup.module(e.source)!==g.source));}
const graph=r.createGraph(spec);source.projectHierarchy(graph,spec);graph.convertValueToString=c=>c.value.getAttribute('label')||'';graph.setTooltips=()=>{};source.configureEdges(graph,spec);graph.getTooltipForCell=()=>'';
r.context.mxUtils.createXmlDocument=()=>({createElement:()=>({attributes:{},setAttribute(k,v){this.attributes[k]=v;},getAttribute(k){return this.attributes[k];}})});
const terminals=spec.edges.map(e=>[e.id,graph.model.getCell(e.id).source.id,graph.model.getCell(e.id).target.id]);const api=focus.configure(graph,spec);
const assertVisible=(state)=>{for(const e of spec.edges)assert.equal(graph.isCellVisible(graph.model.getCell(e.id)),focus.visible(e,state,lookup),e.id);};
assertVisible(api.state);assert.equal(api.counts().details,0);assert.equal(api.proxies.size,lookup.groups.length);
for(const n of spec.nodes){if(n.id===spec.sourcePresentation?.overviewRoot)continue;api.select(n.id);assertVisible(api.state);for(const e of data){const expected=lookup.within(e.source,n.id)||lookup.within(e.target,n.id);assert.equal(graph.isCellVisible(graph.model.getCell(e.id)),expected);}}
api.select(null);assert.equal(api.counts().details,0);api.setAll(true);assertVisible(api.state);assert.equal(api.counts().details,data.length);for(const id of api.proxies.keys())assert.equal(graph.isCellVisible(graph.model.getCell(id)),false);api.setAll(false);
const current=data[0].source;api.updateRun({id:'run1',nodeId:current,trace:[{}]});assert.equal(api.state.scope,lookup.module(current));api.select(null);api.updateRun({id:'run1',nodeId:current,trace:[{}]});assert.equal(api.state.scope,null,'blank reset survives pause/rerender');api.updateRun({id:'run1',nodeId:current,trace:[{},{}]});assert.equal(api.state.scope,lookup.module(current),'next actual step resumes following');api.updateRun(null);assert.equal(api.state.scope,null);
const layout={graph,orientation:r.context.mxConstants.DIRECTION_WEST};r.context.ProbeVisualTheme.configureHierarchy(layout,graph.getDefaultParent());for(const n of spec.nodes)for(const edge of layout.getEdges(graph.model.getCell(n.id)))assert.equal(api.proxies.has(edge.id),false,'summary must not enter native ranking');
api.setLayout(true);for(const e of spec.edges)assert.equal(graph.isCellVisible(graph.model.getCell(e.id)),true);for(const id of api.proxies.keys())assert.equal(graph.isCellVisible(graph.model.getCell(id)),false);api.setLayout(false);
for(const g of lookup.groups){const c=graph.model.getCell(g.id);assert.equal(c.source.id,g.source);assert.equal(c.target.id,g.target);assert.ok(graph.getTooltipForCell(c).includes('不执行'));graph.view.scale=.17;assert.equal(graph.convertValueToString(c),'');graph.view.scale=.55;assert.equal(graph.convertValueToString(c),g.label);const geo=graph.model.getGeometry(c.source),old=geo.x;graph.moveCells([c.source],23,11);assert.equal(c.source.geometry.x,old+23);assert.equal(c.source.id,g.source);}
const fake=[...api.proxies.keys()].map(id=>({getAttribute:()=>id,remove(){this.removed=true;}}));api.stripExport({getElementsByTagName:t=>t==='object'?fake:[]});assert.ok(fake.every(n=>n.removed));
assert.deepEqual(spec.edges.map(e=>[e.id,graph.model.getCell(e.id).source.id,graph.model.getCell(e.id).target.id]),terminals);assert.equal(JSON.stringify(spec),before);
console.log(JSON.stringify({ok:true,dataEdges:data.length,summaryGroups:lookup.groups.length,allAuthoredEndpointsPreserved:true,filteringAndPlayback:true,exportProjectionRemoved:true}));
