'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {loadOfficialRuntime}=require('./native-layout-runtime');
const r=loadOfficialRuntime();r.evaluateFile(path.join(__dirname,'../assets/source-presentation.js'));
const api=r.context.ProbeSourcePresentation;
const spec={sourceModel:{},sourcePresentation:{overviewRoot:'root'},nodes:[{id:'root',role:'container',label:'Project'},{id:'a',parent:'root',role:'container',label:'Area A'},{id:'b',parent:'root',role:'container',label:'Area B'},{id:'deep',parent:'a',role:'container',label:'Real subgroup'},{id:'one',parent:'deep',role:'source',label:'Read request'},{id:'two',parent:'b',role:'terminal',label:'Return result'}],edges:[{id:'transfer',source:'one',target:'two',label:'<script>bad()</script>',kind:'normal'},{id:'dependency',source:'two',target:'one',label:'Shared data',kind:'data',relation:'read'}]};
const original=JSON.stringify(spec),graph=r.createGraph(spec);
const topology=()=>Object.values(graph.model.cells).map(c=>({id:c.id,source:c.source&&c.source.id,target:c.target&&c.target.id,value:c.value&&JSON.stringify(c.value.attributes)}));
const before=topology();api.projectHierarchy(graph,spec);api.projectHierarchy(graph,spec);
assert.equal(JSON.stringify(spec),original);assert.deepEqual(topology(),before);
assert.equal(graph.model.isVisible(graph.model.getCell('root')),false);
assert.equal(graph.model.getParent(graph.model.getCell('a')).id,'1');assert.equal(graph.model.getParent(graph.model.getCell('deep')).id,'a');assert.equal(graph.model.getParent(graph.model.getCell('one')).id,'deep');
const visual=api.visualSpec(spec);assert.equal(visual.nodes.some(n=>n.id==='root'),false);assert.equal(visual.nodes.find(n=>n.id==='a').parent,undefined);assert.equal(spec.nodes.find(n=>n.id==='a').parent,'root');
let selection=[],refreshes=0;const selectionEvents=new r.context.mxEventSource();graph.getSelectionModel=()=>selectionEvents;graph.getSelectionCells=()=>selection;graph.refresh=()=>{refreshes++;};const viewEvents=new r.context.mxEventSource();graph.view.addListener=viewEvents.addListener.bind(viewEvents);graph.convertValueToString=c=>c.value.getAttribute('label');graph.setTooltips=enabled=>{graph.tooltipEnabled=enabled;};api.configureEdges(graph,spec);
assert.equal(graph.convertValueToString(graph.model.getCell('transfer')),'');assert.equal(graph.convertValueToString(graph.model.getCell('dependency')),'');
const select=id=>{selection=id?[graph.model.getCell(id)]:[];selectionEvents.fireEvent(new r.context.mxEventObject(r.context.mxEvent.CHANGE));};
const data=graph.model.getCell('dependency'),control=graph.model.getCell('transfer'),stylesBefore=Object.values(graph.model.cells).map(c=>c.style);
for(const zoom of [.06,.17,.33,.54,.55,1,2.5]){
 graph.view.scale=zoom;viewEvents.fireEvent(new r.context.mxEventObject(r.context.mxEvent.SCALE,'scale',zoom,'previousScale',-1));
 const style=graph.getCellStyle(data),controlStyle=graph.getCellStyle(control);assert.ok(style.strokeWidth*zoom>=1.15-1e-9);assert.ok(controlStyle.strokeWidth*zoom>=1-1e-9);assert.ok(Number(style.opacity)>=85);assert.equal(style.dashed,'1');assert.equal(style.fixDash,'1');assert.ok(Math.abs(Number(style.dashPattern.split(' ')[0])*zoom-5)<1e-9);
 select('a');assert.equal(graph.convertValueToString(data),zoom>=.55?'读取 · Shared data':'','selected labels require readable zoom');assert.equal(graph.convertValueToString(control),zoom>=.55?'<script>bad()</script>':'');assert.equal(graph.getTooltipForCell(data),'读取 · Shared data','hover remains available at every zoom');assert.ok(graph.getCellStyle(data).strokeWidth*zoom>=1.9-1e-9);assert.ok(graph.getCellStyle(data).fontSize*zoom>=11-1e-9);select(null);assert.equal(graph.convertValueToString(data),'');assert.ok(Number(graph.getCellStyle(data).opacity)>=85,'deselection does not hide true data paths');
}
graph.view.scale=.17;graph.useCssTransforms=true;graph.currentScale=.17;graph.view.scale=1;assert.ok(graph.getCellStyle(data).strokeWidth*.17>=1.15-1e-9,'native CSS transform scale is compensated');graph.useCssTransforms=false;graph.view.scale=1;
const convert=graph.convertValueToString;api.configureEdges(graph,spec);assert.equal(graph.convertValueToString,convert,'configuration is idempotent');
assert.deepEqual(Object.values(graph.model.cells).map(c=>c.style),stylesBefore,'selection and zoom styles do not mutate native metadata');assert.ok(refreshes>0);
assert.equal(graph.getTooltipForCell(graph.model.getCell('transfer')),'&lt;script&gt;bad()&lt;/script&gt;');assert.equal(graph.tooltipEnabled,true);assert.deepEqual(topology(),before);
const internalBefore=JSON.stringify(graph.model.getGeometry(graph.model.getCell('one')));api.composeOrdered(graph,spec);
const ga=graph.model.getGeometry(graph.model.getCell('a')),gb=graph.model.getGeometry(graph.model.getCell('b'));
assert.ok(ga.y<gb.y||(ga.y===gb.y&&ga.x<gb.x));assert.equal(JSON.stringify(graph.model.getGeometry(graph.model.getCell('one'))),internalBefore);assert.deepEqual(topology(),before);
const positions=JSON.stringify([ga,gb]);api.composeOrdered(graph,spec);assert.equal(JSON.stringify([graph.model.getGeometry(graph.model.getCell('a')),graph.model.getGeometry(graph.model.getCell('b'))]),positions);
const design={nodes:[]};assert.equal(api.visualSpec(design),design);
const element=tag=>({tag,children:[],textContent:'',append(...children){this.children.push(...children);}});r.context.document.createElement=element;
const cite={path:'src/main.js',lines:[1,2],revision:'a'.repeat(40),sha256:'b'.repeat(64),verification:'files-and-pinned-blobs-checked'};
const evidence=api.evidenceDetails({claims:[{statement:'<img onerror=bad()>',status:'observed',evidence:[cite]}],relationships:[],boundaries:[]},spec);
assert.equal(evidence.tag,'details');assert.equal(evidence.open,undefined);assert.equal(evidence.children[0].tag,'summary');
const strings=[];function walk(e){strings.push(e.textContent);e.children.forEach(walk);}walk(evidence);assert.ok(strings.includes('代码中观察到：<img onerror=bad()>'));assert.ok(strings.some(x=>x.includes('src/main.js:1–2')));
const related={id:'dependency',source:'two',target:'one',relation:'read',claims:[]};
const nestedSpec={...spec,nodes:spec.nodes.map(n=>({...n,docs:{sourceEvidence:{relationships:n.id==='one'?[related]:[]}}}))};
const nestedEvidence=api.evidenceDetails({claims:[],relationships:[],boundaries:[]},nestedSpec,'a');strings.length=0;walk(nestedEvidence);assert.ok(strings.includes('相邻关系（含内部节点） · 1 条'));assert.ok(strings.includes('读取：Return result → Read request'));assert.equal(JSON.stringify(spec),original);
console.log(JSON.stringify({ok:true,checks:['source spec unchanged','all node/edge IDs and endpoints preserved','root display projection idempotent','real nesting retained','default cross/data labels suppressed with escaped hover','default read/write/data routes have screen-space width and contrast floors','selected nested links stay emphasized while labels are zoom-gated','nested relationships remain in the existing inspector','zoom and selection leave model styles and topology untouched','evidence collapsed and text-only','source area order retained and idempotent','design path untouched'],evidence:'Official native model + DOM double; browser visual review still required'}));
